### ISSUE TITLE
A problem related to the headphones on the Dell Latitude E7440

### ISSUE THREAD

**Issue by mahmoudelemam1** [ameeno/ameeno#1]
Hey guru, I want help with this headphone issue that crashes and returns to work once the system sleeps. I've tried a lot and couldn't find solutions. Any help would be greatly appreciated
Dell Ltitude E7440 i5
MacOS Catalina 10.15.6 Clover

**Comment by ameeno** [comment]
Hello, have you tried OpenCore? Clover does not get as much love anymore
