### ISSUE TITLE
macOS kernel panics (?) after going to sleep when the lid closes

### ISSUE THREAD

**Issue by Noxyntious** [ameeno/ameeno#2]
Specs:
Dell Latitude E7240
4GB RAM
Intel Core i5-4210U
Intel HD Graphics 4400
---
macOS kernel panics after going to sleep.
After opening the lid, the computer freezes at a totally black screen with no way of waking it up, without restarting the computer with the power button. When it boots back up, there is text that says "This system was automatically rebooted after panic" in Clover. After booting to macOS and logging in, there are popups saying "You restarted your computer because of a problem." I've ran the shell script from the repository, but that didn't fix anything.
Any fixes?
Thanks!

**Comment by ameeno** [comment]
Sorry, No longer use that machine, - Switched to fedora

**Comment by Noxyntious** [comment]
All good, I figured out that enabling "Block Sleep" in BIOS fixes this.
